export const ADD__PRODUCT = "ADD__PRODUCT";
export const REMOVE__PRODUCT = "REMOVE__PRODUCT";
export const FILTER__PRODUCTS = "FILTER__PRODUCTS";
export const FETCH__PRODUCT = "FETCH__PRODUCT";
export const DECREASE__PRODUCT = "DECREASE__PRODUCT";
